#!/bin/sh
#
set -e

# 
apt install -y nginx

#
systemctl enable nginx

# move config
mv /tmp/nginx/nginx.conf /etc/nginx/nginx.conf
mv /tmp/nginx/default.conf /etc/nginx/conf.d/default.conf
mv /tmp/nginx/potato.conf /etc/nginx/conf.d/potato.conf