#!/usr/bin/env bash

#
apt install ca-certificates -y
apt install gnupg gnupg2 -y
apt install gpg-agent -y
touch /etc/apt/sources.list.d/nginx.list
echo "deb https://nginx.org/packages/mainline/ubuntu bionic nginx" > /etc/apt/sources.list.d/nginx.list
echo "#deb-src https://nginx.org/packages/mainline/ubuntu bionic nginx" >> /etc/apt/sources.list.d/nginx.list
curl -fsSL https://nginx.org/keys/nginx_signing.key | apt-key add -
useradd -r nginx --shell=/usr/sbin/nologin
apt-get install nginx -y

# Create service
echo "[Unit]" > /lib/systemd/system/nginx.service
echo "Description=The NGINX HTTP and reverse proxy server" >> /lib/systemd/system/nginx.service
echo "Before=netdata.service trojan.service" >> /lib/systemd/system/nginx.service
echo "After=syslog.target network.target remote-fs.target nss-lookup.target" >> /lib/systemd/system/nginx.service
echo "[Service]" >> /lib/systemd/system/nginx.service
echo "Type=forking" >> /lib/systemd/system/nginx.service
echo "PIDFile=/run/nginx.pid" >> /lib/systemd/system/nginx.service
echo "ExecStartPre=/usr/sbin/nginx -t" >> /lib/systemd/system/nginx.service
echo "ExecStart=/usr/sbin/nginx" >> /lib/systemd/system/nginx.service
echo "ExecReload=/usr/sbin/nginx -s reload" >> /lib/systemd/system/nginx.service
echo "ExecStop=/bin/kill -s QUIT \$MAINPID" >> /lib/systemd/system/nginx.service
echo "PrivateTmp=true" >> /lib/systemd/system/nginx.service
echo "LimitNOFILE=65536" >> /lib/systemd/system/nginx.service
echo "Restart=on-failure" >> /lib/systemd/system/nginx.service
echo "RestartSec=3s" >> /lib/systemd/system/nginx.service
echo "[Install]" >> /lib/systemd/system/nginx.service
echo "WantedBy=multi-user.target" >> /lib/systemd/system/nginx.service

#
systemctl enable nginx
mkdir -p /usr/share/nginx/cache
mkdir -p /usr/share/nginx/php_cache
mkdir -p /etc/nginx
echo "user nginx;" > /etc/nginx/nginx.conf
echo "worker_processes auto;" >> /etc/nginx/nginx.conf
echo "error_log /var/log/nginx/error.log warn;" >> /etc/nginx/nginx.conf
echo "pid /run/nginx.pid;" >> /etc/nginx/nginx.conf
echo "include /etc/nginx/modules-enabled/*.conf;" >> /etc/nginx/nginx.conf
echo "events {" >> /etc/nginx/nginx.conf
echo "  #worker_connections 51200;" >> /etc/nginx/nginx.conf
echo "  use epoll;" >> /etc/nginx/nginx.conf
echo "  multi_accept on;" >> /etc/nginx/nginx.conf
echo "}" >> /etc/nginx/nginx.conf
echo "http {" >> /etc/nginx/nginx.conf
echo "  #proxy_cache_path /usr/share/nginx/cache levels=1:2 keys_zone=my_cache:10m max_size=100m inactive=60m use_temp_path=off;" >> /etc/nginx/nginx.conf
echo "  #proxy_cache_valid 200 302 10m;" >> /etc/nginx/nginx.conf
echo "  #proxy_cache_valid 404      1m;" >> /etc/nginx/nginx.conf
echo "  #proxy_cache_bypass \$http_pragma    \$http_authorization    \$http_cache_control;" >> /etc/nginx/nginx.conf
echo "  #proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;" >> /etc/nginx/nginx.conf
echo "  #proxy_cache_revalidate on;" >> /etc/nginx/nginx.conf
echo "  #proxy_cache_background_update on;" >> /etc/nginx/nginx.conf
echo "  #proxy_cache_lock on;" >> /etc/nginx/nginx.conf
echo "  #proxy_cache my_cache;" >> /etc/nginx/nginx.conf
echo "  #fastcgi_cache_path /usr/share/nginx/php_cache levels=1:2 keys_zone=phpcache:10m max_size=100m inactive=60m use_temp_path=off;" >> /etc/nginx/nginx.conf
echo "  #fastcgi_cache_valid 200 302 10m;" >> /etc/nginx/nginx.conf
echo "  #fastcgi_cache_valid 404      1m;" >> /etc/nginx/nginx.conf
echo "  #fastcgi_cache_bypass \$http_pragma    \$http_authorization    \$http_cache_control;" >> /etc/nginx/nginx.conf
echo "  #fastcgi_cache_use_stale error timeout updating invalid_header http_500 http_503;" >> /etc/nginx/nginx.conf
echo "  #fastcgi_cache_revalidate on;" >> /etc/nginx/nginx.conf
echo "  #fastcgi_cache_background_update on;" >> /etc/nginx/nginx.conf
echo "  #fastcgi_cache_lock on;" >> /etc/nginx/nginx.conf
echo "  #fastcgi_cache phpcache;" >> /etc/nginx/nginx.conf
echo "  #fastcgi_cache_key "\$scheme\$proxy_host\$request_uri";" >> /etc/nginx/nginx.conf
echo "  autoindex_exact_size off;" >> /etc/nginx/nginx.conf
echo "  http2_push_preload on;" >> /etc/nginx/nginx.conf
echo "  aio threads;" >> /etc/nginx/nginx.conf
echo "  charset UTF-8;" >> /etc/nginx/nginx.conf
echo "  tcp_nodelay on;" >> /etc/nginx/nginx.conf
echo "  tcp_nopush on;" >> /etc/nginx/nginx.conf
echo "  server_tokens off;" >> /etc/nginx/nginx.conf
echo "  " >> /etc/nginx/nginx.conf
echo "  proxy_intercept_errors on;" >> /etc/nginx/nginx.conf
echo "  proxy_http_version 1.1;" >> /etc/nginx/nginx.conf
echo "  proxy_ssl_protocols TLSv1.2 TLSv1.3;" >> /etc/nginx/nginx.conf
echo "  proxy_set_header Host \$http_host;" >> /etc/nginx/nginx.conf
echo "  proxy_set_header X-Real-IP \$remote_addr;" >> /etc/nginx/nginx.conf
echo "  proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;" >> /etc/nginx/nginx.conf
echo "  include /etc/nginx/mime.types;" >> /etc/nginx/nginx.conf
echo "  default_type application/octet-stream;" >> /etc/nginx/nginx.conf
echo "  access_log /var/log/nginx/access.log;" >> /etc/nginx/nginx.conf
echo "  log_format  main  '\$remote_addr - \$remote_user [\$time_local] "\$request" '" >> /etc/nginx/nginx.conf
echo "    '\$status \$body_bytes_sent "\$http_referer" '" >> /etc/nginx/nginx.conf
echo "    '"\$http_user_agent" "\$http_x_forwarded_for"';" >> /etc/nginx/nginx.conf
echo "  sendfile on;" >> /etc/nginx/nginx.conf
echo "  gzip on;" >> /etc/nginx/nginx.conf
echo "  gzip_proxied any;" >> /etc/nginx/nginx.conf
echo "  gzip_types *;" >> /etc/nginx/nginx.conf
echo "  gzip_comp_level 9;" >> /etc/nginx/nginx.conf
echo "  include /etc/nginx/conf.d/default.conf;" >> /etc/nginx/nginx.conf
echo "}" >> /etc/nginx/nginx.conf

echo "server {" > /etc/nginx/conf.d/default.conf
echo "    listen 127.0.0.1:81 http2;" >> /etc/nginx/conf.d/default.conf
echo "    server_name _;" >> /etc/nginx/conf.d/default.conf
echo "    add_header Strict-Transport-Security \"max-age=31536000; includeSubDomains; preload\" always;" >> /etc/nginx/conf.d/default.conf
echo "    location / {" >> /etc/nginx/conf.d/default.conf
echo "        proxy_pass http://unix:/run/cloudreve.sock;" >> /etc/nginx/conf.d/default.conf
echo "        client_max_body_size 20000m; " >> /etc/nginx/conf.d/default.conf
echo "        proxy_set_header X-Forwarded-For 127.0.0.1;" >> /etc/nginx/conf.d/default.conf
echo "        proxy_set_header Host 127.0.0.1:443;     " >> /etc/nginx/conf.d/default.conf
echo "        proxy_redirect     off;" >> /etc/nginx/conf.d/default.conf
echo "        proxy_buffer_size          64k; " >> /etc/nginx/conf.d/default.conf
echo "        proxy_buffers              32 32k; " >> /etc/nginx/conf.d/default.conf
echo "        proxy_busy_buffers_size    128k;  " >> /etc/nginx/conf.d/default.conf
echo "    }" >> /etc/nginx/conf.d/default.conf
echo "}" >> /etc/nginx/conf.d/default.conf