#!/usr/bin/env bash
set -e

# install package
apt install -y websockify

#
sed -i "$ i\screen -dmS trojanwstotcp websockify 0.0.0.0:80 127.0.0.1:443 --cert=/opt/certificates/fullchain.crt --key=/opt/certificates/private.key" /etc/userd.local